### ISSUE TITLE
adding extra plugins

### ISSUE THREAD

**Issue by balabanahmetfevzi** [warp-contracts/warp-contracts-plugins#5]
In our project, we needed to use npm snarkjs package in contracts, but bundling snarkjs proved too cumbersome. Can we add this dependency as a plugin? [snarkjs](https://www.npmjs.com/package/snarkjs)

**Comment by asiaziola** [comment]
custom SmartWeave extensions plugin configuration has been enabled in `warp-contracts@1.2.42`. Here is the explanation https://github.com/warp-contracts/warp/releases/tag/v1.2.41
